apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template: 
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: awspsels/backend  #### AWS Backend Image
        ports:
        - name: http
          containerPort: 5000